name: Deploy Gentlemen's Club Barbershop to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Configure GitHub Pages (auto-enable)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      # 3. Upload the static site files
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./lovable-export   # Folder containing index.html

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
