name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # deploy every time you push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Publish
        uses: actions/deploy-pages@v4
